###
# Makefile
# Project 2a: WhooSH
###

CC = gcc
CFLAGS = -O -Wall -o 


# Make file
whoosh: whoosh.c
	$(CC) $(CFLAGS) whoosh whoosh.c
	
# Test
test:
	./whoosh
	
# Clean
clean:
	rm -f *~ *.out *.err whoosh


